AWSTemplateFormatVersion: 2010-09-09
Description: ECS Fargate service in private subnets
Parameters:
  ##Digiroad-OTH-kehitys
  NetworkStackName:
    Description: Name of the network stack
    Type: String
  ApplicationName:
    Description: Name of the application (no whitespace or special characters)
    Type: String
  DevDatabaseURL:
    Description: Database url
    Type: String
  DevDatabaseUser:
    Description: Database user
    Type: String
  ServiceCPU:
    Description: Service CPU, vayla defaut is 256
    Default: 256
    Type: number
  ServiceMemory:
    Description: Service memory, vayla defaut is 512
    Default: 512
    Type: number
  Environment:
    Description: "Environment of the application, that these resources are created for. Used when tagging the resources"
    Type: String
  Owner:
    Description: "Owner of the of application, that these resources are created for. Used when tagging the resources"
    Type: String
  Project:
    Description: "Project of the of application, that these resources are created for. Used when tagging the resources"
    Type: String
  ContainerTag:
    Type: String
    Default: latest
    Description: Tag of the container
  ContainerPort:
    Type: Number
    Default: 80
    Description: Port of the container
  RepositoryURI:
    Type: String
    Description: URI to repository, where the container is
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group, that is protecting the load balancer. This probably will allow traffic from the TGW
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group, that is protecting the containers. This probably will allow traffic only from the VPC
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['-', [!Ref ApplicationName, 'ECS-Cluster-Private']]
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'ECS-Cluster']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', ['/ecs/', !Ref ApplicationName, '-ECS-logs']]
      RetentionInDays: 14

  # This is a role which is used by the ECS tasks themselves.
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                # Allow the ECS Tasks to download images from ECR
                - 'ecr:GetAuthorizationToken'
                - 'ecr:BatchCheckLayerAvailability'
                - 'ecr:GetDownloadUrlForLayer'
                - 'ecr:BatchGetImage'

                # Allow the ECS tasks to upload logs to CloudWatch
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'

  ECSTask:
    Type: AWS::ECS::TaskDefinition
    DependsOn: ECSLogGroup
    Properties:
      Family: !Ref ApplicationName
      # Adjust these according to the needs of your applications containers
      Cpu: !Ref ServiceCPU
      Memory: !Ref ServiceMemory
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      # TaskRoleArn: # Enable and create this role, if your container needs access to other AWS services like SQS, SES, DynamoDB etc.
      NetworkMode: awsvpc # This is the only possible option with Fargate mode, but set here to remind of this behaviour
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        # First container. You can add several containers to one task. You would probably only add sidecar containers though
        - Name: !Ref ApplicationName
          Image: !Join [':', [!Ref RepositoryURI, !Ref ContainerTag]]
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          # If you want to pass environment variables to the container, uncomment and modify these:
           Environment:
             - Name: REGION
               Value: !Ref AWS::Region
             - Name: speedLimitProvider
               Value: fi.liikennevirasto.digiroad2.service.linearasset.SpeedLimitService
             - Name: userProvider
               Value: fi.liikennevirasto.digiroad2.dao.PostGISUserProvider
             - Name: municipalityProvider
               Value: fi.liikennevirasto.digiroad2.dao.PostGISMunicipalityProvider
             - Name: eventBus
               Value: fi.liikennevirasto.digiroad2.DigiroadEventBus
             - Name: useVVHGeometry
               Value: true
             - Name: VVHServiceHost
               Value: 172.17.204.38:6080 #haproxy.vayla.fi
             - Name: VVHRestApiEndPoint
               Value: http://172.17.204.38:6080/arcgis/rest/services/VVH_OTH_TEST/ #https://haproxy.vayla.fi:2027/vvhdata/
             - Name: VVHProdRestApiEndPoint
               Value: http://172.17.204.39:6080/arcgis/rest/services/VVH_OTH/
             - Name: VVHRoadlink.frozen
               Value: false
             - Name: viiteRestApiEndPoint
               Value: http://localhost:9080/viite/api/viite/ #?
             - Name: authenticationTestMode
               Value: true
             - Name: VKMUrl
               Value: http://oag.vayla.fi
             - Name: tierekisteriRestApiEndPoint
               Value: http://testioag.vayla.fi:8081/trrest/devtest/ #?
             - Name: tierekisteri.enabled
               Value: true
             - Name: vallu.server.sending_enabled
               Value: true
             - Name: vallu.server.address
               Value: http://localhost:9002
             - Name: viite.importTimeStamp
               Value: 1510876800000
             - Name: http.proxySet
               Value: true
             - Name: http.proxyHost
               Value: 127.0.0.1
             - Name: http.proxyPort
               Value: 3128
             - Name: http.nonProxyHosts
               Value: 172.17.*|localhost|127.*
             - Name: feedbackAssetsEndPoint
               Value: http://devtest.vayla.fi/digiroad/
             - Name: bonecp.jdbcUrl
               Value: ref DevDatabaseURL
             - Name: bonecp.username
               Value: ref DevDatabaseUser
             - Name: authentication.basic.username
               Value: "kalpa"
             - Name: authentication.serviceRoad.basic.username
               Value: "livi"
             - Name: authentication.municipality.basic.username
               Value: "kalpa"
             - Name: tierekisteri.username
               Value: "trrest"
             - Name: tierekisteri.old.username
               Value: "trrest"
             - Name: viite.username
               Value: "kalpa"
          Secrets:
            - Name: bonecp.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/bonecp.password"
            - Name: authentication.basic.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/authentication.basic.password"
            - Name: authentication.serviceRoad.basic.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/bonecp.password"
            - Name: authentication.municipality.basic.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/authentication.serviceRoad.basic.password"
            - Name: tierekisteri.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/tierekisteri.password"
            - Name: tierekisteri.old.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/tierekisteri.old.password"
            - Name: viite.password
              ValueFrom: "arn:aws:ssm:eu-west-1:475079312496:parameter/dev/viite.password"

          Essential: true # One of the container need to be essential. So, if you'd add another container in this task, it's Essential -value should be false.
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          # Adjust this according to the need of your container
          Memory: !Ref ServiceMemory
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'ECS-Task']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  PrivateLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 30
        - Key: routing.http2.enabled
          Value: true
      Subnets:
        - Fn::ImportValue:
            !Join ['-', [!Ref NetworkStackName, 'Subnet1-Id']]
        - Fn::ImportValue:
            !Join ['-', [!Ref NetworkStackName, 'Subnet2-Id']]
      SecurityGroups: [!Ref LoadBalancerSecurityGroup]
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'LoadBalancer']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  PrivateLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - PrivateLoadBalancer
      - TargetGroup
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: 'forward'
      LoadBalancerArn: !Ref PrivateLoadBalancer
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'LoadBalancer-Listener']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: PrivateLoadBalancer
    Properties:
      HealthCheckIntervalSeconds: 300
      HealthCheckPath: /  # If you have a more sophisticated container health check endpoint, add its path here
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      TargetType: ip
      Name: !Join ['-', [!Ref ApplicationName, 'TargetGroup']]
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 10
      VpcId:
        Fn::ImportValue:
          !Join ['-', [!Ref NetworkStackName, 'VPC-Id']]
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'LoadBalancer-TargetGroup']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: PrivateLoadBalancerListener
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
      Conditions:
        - Field: path-pattern
          Values: ['*']
      ListenerArn: !Ref PrivateLoadBalancerListener
      Priority: 1
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'LoadBalancer-Rule']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  EcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSCluster
      - ECSTask
      - TargetGroup
      - PrivateLoadBalancerListener
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Join ['-', [!Ref ApplicationName, 'ECS-Service-Private']]
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - Fn::ImportValue:
                !Join ['-', [!Ref NetworkStackName, 'Subnet1-Id']]
            - Fn::ImportValue:
                !Join ['-', [!Ref NetworkStackName, 'Subnet2-Id']]
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTask
      LoadBalancers:
        - ContainerName: !Ref ApplicationName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'ECS-Service']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref ApplicationName, 'LoadBalancer']]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

Outputs:
  ALBDNSName:
    Description: DNSname for the private Application Load Balancer
    Value: !GetAtt PrivateLoadBalancer.DNSName
