AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  NetworkStackName:
    Description: Name of the network stack
    Type: String
  DigiroadDatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Databases security group
  VpcIDOfSystem:
    Type: AWS::EC2::VPC::Id
    Description: VPC of your system

Resources:
  JobQueueAdHoc:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: "AdHoc"
      Priority: 1
      ComputeEnvironmentOrder:
      - Order: 1
        ComputeEnvironment:
          Ref: ComputeEnvironment
  JobQueueUpdateIncompleteList:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: "UpdateIncompleteList"
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment:
            Ref: ComputeEnvironment

  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: "BatchCompute"
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 32
        Subnets:
          - Fn::ImportValue:
              !Join [ '-', [ !Ref NetworkStackName, 'Subnet1-Id' ] ]
          - Fn::ImportValue:
              !Join [ '-', [ !Ref NetworkStackName, 'Subnet2-Id' ] ]
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
      ServiceRole:
        Ref: BatchServiceRole

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allaw inbound to port 80 and 5432, Outbound to everything
      GroupName: BatchSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref DigiroadDatabaseSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcIDOfSystem

#  BatchProcessingLambdaInvokeFunction:
#    Type: AWS::Lambda::Function
#    Properties:
#      FunctionName: BatchProcessingLambdaInvokeFunction
#      Handler: index.lambda_handler
#      Runtime: d
#      MemorySize: 128
#      Timeout: 30
#      Role: nodejs10.x
#        Fn::GetAtt:
#          - LambdaExecutionRole
#          - Arn
#      Code:
#        ZipFile: |
#          code
#
#  # CloudWatch Event Rule for build trigger
#  CloudWatcEventRule:
#    Type: AWS::Events::Rule
#    Properties:
#      Description: "This event rule triggers the batch on event"
#      EventPattern: ""
#      State: "ENABLED"
#      Targets:
#        -
#          Arn: {'Fn::GetAtt': [BatchProcessingLambdaInvokeFunction, Arn]}
#          Id: cloudwatch-codebuild-eventrules
#          RoleArn: !GetAtt LambdaExecutionRole.Arn
#
#  LambdaExecutionRole:
#    Type: AWS::IAM::Role
#    Properties:
#      RoleName: LambdaBatch
#      AssumeRolePolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Action:
#              - sts:AssumeRole
#            Effect: Allow
#            Principal:
#              Service:
#                - lambda.amazonaws.com
#      ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/AWSLambdaExecute
#      Path: /
#      Policies:
#        - PolicyName: "BatchLambda"
#          PolicyDocument:
#            Statement:
#              - Effect: Allow
#                Action:
#                  - "batch:SubmitJob"
#                  - "batch:Describe*"
#                  - "batch:List*"
#                  - "batch:UpdateJobQueue"
#                  - "batch:TerminateJob"
#                  - "batch:CancelJob"
#                Resource: *

  BatchTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: AmazonBatchECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'

                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'

                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                Resource: '*'

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

Outputs:
  BatchTaskRoleARN:
    Description: BatchTaskRole
    Value: !GetAtt BatchTaskRole.Arn
  BatchExecutionArn:
    Description: BatchServiceRole
    Value: !GetAtt BatchServiceRole.Arn
